server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.123.122:3306/iot?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: admin
    password: 123456

# mybatis配置
mybatis-plus:
  # 全局配置
  global-config:
    db-config:
      # 逻辑删除全局字段 (默认无 设置会自动扫描实体字段)
      logic-delete-field: delFlag
      # 逻辑删除全局值（默认 1、表示已删除）
      logic-delete-value: 1
      # 逻辑未删除全局值（默认 0、表示未删除）
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句
    #设置当查询结果值为null时，同样映射该查询字段给map。
    call-setters-on-nulls: true
    cache-enabled: true #开启二级缓存
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.isoftstone.manage.entity
